### ISSUE TITLE
Windows用户管理初体验 - Rekord-Blog

### ISSUE THREAD

**Issue by Crazyokd** [Crazyokd/rekord-blog#5]
http://sxrekord.com/ie-of-Windows-user-mana/ 

 这几天不知道为什么，每次打开cmd命令提示符，看到Users后面跟着的86182越发不爽，我知道这串数字代表着我这台windows笔记本的用户名。那么问题来了，对于有取名强迫症的我来说，用户名是这么一串随意且无意义的数字当然是无法忍受的。只想不做一直是我的弱点，想改又改不了。但是这几天正好cmd用的也比较频繁，契机摆在眼前，这次我还是没把它放过。下面开干：首先必须找到用户名设置的相关入口，最直接的

**Comment by JaxVanYang** [comment]
挖
