### ISSUE TITLE
docker on wsl2 - Rekord-Blog

### ISSUE THREAD

**Issue by Crazyokd** [Crazyokd/rekord-blog#52]
https://sxrekord.com/docker-on-wsl2/? 

 installation:curl -sSL https://get.docker.com/ | sh  start/stop/restart docker daemon:sudo service docker start sudo service docker stop sudo service docker restart  access docker with no su

**Comment by JaxVanYang** [comment]
为什么不用包管理的 Docker，或者 Docker Desktop for Windows

**Comment by Crazyokd** [comment]
> @JaxVanYang
> 为什么不用包管理的 Docker，或者 Docker Desktop for Windows 

包管理的 Docker不了解，但 Docker Desktop for Windows 是刻意不用的。

**Comment by JaxVanYang** [comment]
> > @JaxVanYang
> > 为什么不用包管理的 Docker，或者 Docker Desktop for Windows
> 
> 包管理的 Docker不了解，但 Docker Desktop for Windows 是刻意不用的。

manual install 管理起来应该没有系统包管理方便。
